### ISSUE TITLE
.envrc doesn't work on macOS

### ISSUE THREAD

**Issue by antja0** [LIFTE-H2/GPTBot#3]
Occurred on mac, probably same issue with windows.

I got around this by running export commands in terminal before running deployment.

I don't know what would be a good cross-env solution to load env from file. Perhaps [cross-env](https://github.com/kentcdodds/cross-env) ?

**Comment by olivierpichon** [comment]
Hi @antja0,

As indicated in the README, to get the `.envrc` file sourced you can install a tool like direnv: https://direnv.net/
